i=complex(0,1);
t=linspace(0,1,100);
s=sin(2*pi*18*t);
x=abs(fft(s));
y=s.*exp(i*2*pi*3*t);
z=abs(fft(y));
subplot(3,2,1);
stem(t,s);
title('signal');
subplot(3,2,2);
stem(x);
title('absolute signal');
subplot(3,2,3);
stem(t,y);
title('shifted signal');
subplot(3,2,4);
stem(z);
title('shift freq');
subplot(3,2,5);
plot(t);